#ifndef PINS_H
#define PINS_H

#define PIN_DOOR_SENSOR A2
#define PIN_OVERHEAT_SENSOR A3
#define PIN_LEAK_SENSOR A4
#define PIN_LEVEL_SENSOR A5

#define PIN_RELAY_HEAT 4
#define PIN_RELAY_PUMP 5
#define PIN_RELAY_VALVE 6
#define PIN_RELAY_WASH 7
#define PIN_RELAY_POWER 9
#define PIN_RELAY_SOAP 13

#define PIN_LCD_DATA 8

#define WLAN_RX 10
#define WLAN_TX 11

#define ENCODER_RIGHT_PIN 3
#define ENCODER_LEFT_PIN 2
#define ENCODER_BUTTON_PIN A6

#endif