#ifndef VALUES_H
#define VALUES_H

// On/off sensors
#define SENSOR_BOOL_DOOR 0
#define SENSOR_BOOL_LEAK 1
#define SENSOR_BOOL_LEVEL 2
#define SENSOR_BOOL_OVERHEAT 3

// Sensors with value
#define SENSOR_VAL_TEMPERATURE 0
#define SENSOR_VAL_QUALITY 1

// Relays
#define RELAY_PUMP 0
#define RELAY_SOAP 1
#define RELAY_WASH 2
#define RELAY_HEAT 3
#define RELAY_POWER 4

// Lcd center
#define LCD_TEXT_POS_CENTER_TOP 0
#define LCD_TEXT_POS_CENTER_BOTTOM 1

#define LCD_ICON_POS_LARGE_CENTER_ICON 1

// Right top icons
#define LCD_ICON_POS_SMALL_RIGHT_TOP_ONE 14

#define LCD_ICON_POS_SMALL_RIGHT_TOP_TWO_1 15
#define LCD_ICON_POS_SMALL_RIGHT_TOP_TWO_2 16

#define LCD_ICON_POS_SMALL_RIGHT_TOP_TREE_1 15
#define LCD_ICON_POS_SMALL_RIGHT_TOP_TREE_2 14
#define LCD_ICON_POS_SMALL_RIGHT_TOP_TREE_3 16

#define LCD_ICON_POS_SMALL_RIGHT_TOP_FOUR_1 19
#define LCD_ICON_POS_SMALL_RIGHT_TOP_FOUR_2 20
#define LCD_ICON_POS_SMALL_RIGHT_TOP_FOUR_3 21
#define LCD_ICON_POS_SMALL_RIGHT_TOP_FOUR_4 22

// Right bottom icons
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_ONE 23

#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_TWO_1 25
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_TWO_2 24

#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_TREE_1 27
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_TREE_2 23
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_TREE_3 26

#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_FOUR_1 28
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_FOUR_2 29
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_FOUR_3 30
#define LCD_ICON_POS_SMALL_RIGHT_BOTTOM_FOUR_4 31

// Left bottom circle icons
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_ONE 32

#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_TWO_1 33
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_TWO_2 34

#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_TREE_1 36
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_TREE_2 32
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_TREE_3 35

#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_FOUR_1 = 37
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_FOUR_2 = 38
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_FOUR_3 = 39
#define LCD_ICON_POS_SMALL_LEFT_BOTTOM_FOUR_4 = 40

// Left top circle icons
#define LCD_ICON_POS_SMALL_LEFT_TOP_ONE 0

#define LCD_ICON_POS_SMALL_LEFT_TOP_TWO_1 7
#define LCD_ICON_POS_SMALL_LEFT_TOP_TWO_2 6

#define LCD_ICON_POS_SMALL_LEFT_TOP_TREE_1 8
#define LCD_ICON_POS_SMALL_LEFT_TOP_TREE_2 0
#define LCD_ICON_POS_SMALL_LEFT_TOP_TREE_3 9

#define LCD_ICON_POS_SMALL_LEFT_TOP_FOUR_1 10
#define LCD_ICON_POS_SMALL_LEFT_TOP_FOUR_2 11
#define LCD_ICON_POS_SMALL_LEFT_TOP_FOUR_3 12
#define LCD_ICON_POS_SMALL_LEFT_TOP_FOUR_4 13

// Background image positions

#define LCD_BACKGROUND_POS_RIGHT_TOP 5,
#define LCD_BACKGROUND_POS_RIGHT_BOTTOM 4
#define LCD_BACKGROUND_POS_LEFT_BOTTOM 3
#define LCD_BACKGROUND_POS_LEFT_TOP 2

// Background images

// Circle right top
#define LCD_BACKGROUND_RIGHT_TOP_EMPTY 62

#define LCD_BACKGROUND_RIGHT_TOP_ONE 60
#define LCD_BACKGROUND_RIGHT_TOP_ONE_SELECTED 61

#define LCD_BACKGROUND_RIGHT_TOP_TWO 48
#define LCD_BACKGROUND_RIGHT_TOP_TWO_1_SELECTED 49
#define LCD_BACKGROUND_RIGHT_TOP_TWO_2_SELECTED 50

#define LCD_BACKGROUND_RIGHT_TOP_THREE 51
#define LCD_BACKGROUND_RIGHT_TOP_THREE_1_SELECTED 52
#define LCD_BACKGROUND_RIGHT_TOP_THREE_2_SELECTED 53
#define LCD_BACKGROUND_RIGHT_TOP_THREE_3_SELECTED 54

#define LCD_BACKGROUND_RIGHT_TOP_FOUR 55
#define LCD_BACKGROUND_RIGHT_TOP_FOUR_1_SELECTED 56
#define LCD_BACKGROUND_RIGHT_TOP_FOUR_2_SELECTED 57
#define LCD_BACKGROUND_RIGHT_TOP_FOUR_3_SELECTED 58
#define LCD_BACKGROUND_RIGHT_TOP_FOUR_4_SELECTED 59

// Circle right bottom
#define LCD_BACKGROUND_RIGHT_BOTTOM_EMPTY 63

#define LCD_BACKGROUND_RIGHT_BOTTOM_ONE 46
#define LCD_BACKGROUND_RIGHT_BOTTOM_ONE_SELECTED 47

#define LCD_BACKGROUND_RIGHT_BOTTOM_TWO 34
#define LCD_BACKGROUND_RIGHT_BOTTOM_TWO_1_SELECTED 35
#define LCD_BACKGROUND_RIGHT_BOTTOM_TWO_2_SELECTED 36

#define LCD_BACKGROUND_RIGHT_BOTTOM_THREE 37
#define LCD_BACKGROUND_RIGHT_BOTTOM_THREE_1_SELECTED 38
#define LCD_BACKGROUND_RIGHT_BOTTOM_THREE_2_SELECTED 39
#define LCD_BACKGROUND_RIGHT_BOTTOM_THREE_3_SELECTED 40

#define LCD_BACKGROUND_RIGHT_BOTTOM_FOUR 41
#define LCD_BACKGROUND_RIGHT_BOTTOM_FOUR_1_SELECTED 42
#define LCD_BACKGROUND_RIGHT_BOTTOM_FOUR_2_SELECTED 43
#define LCD_BACKGROUND_RIGHT_BOTTOM_FOUR_3_SELECTED 44
#define LCD_BACKGROUND_RIGHT_BOTTOM_FOUR_4_SELECTED 45

// Circle left bottom
#define LCD_BACKGROUND_LEFT_BOTTOM_EMPTY 64

#define LCD_BACKGROUND_LEFT_BOTTOM_ONE 32
#define LCD_BACKGROUND_LEFT_BOTTOM_ONE_SELECTED 33

#define LCD_BACKGROUND_LEFT_BOTTOM_TWO 20
#define LCD_BACKGROUND_LEFT_BOTTOM_TWO_1_SELECTED 21
#define LCD_BACKGROUND_LEFT_BOTTOM_TWO_2_SELECTED 22

#define LCD_BACKGROUND_LEFT_BOTTOM_THREE 23
#define LCD_BACKGROUND_LEFT_BOTTOM_THREE_1_SELECTED 24
#define LCD_BACKGROUND_LEFT_BOTTOM_THREE_2_SELECTED 25
#define LCD_BACKGROUND_LEFT_BOTTOM_THREE_3_SELECTED 26

#define LCD_BACKGROUND_LEFT_BOTTOM_FOUR 27
#define LCD_BACKGROUND_LEFT_BOTTOM_FOUR_1_SELECTED 28
#define LCD_BACKGROUND_LEFT_BOTTOM_FOUR_2_SELECTED 29
#define LCD_BACKGROUND_LEFT_BOTTOM_FOUR_3_SELECTED 30
#define LCD_BACKGROUND_LEFT_BOTTOM_FOUR_4_SELECTED 31

// Circle left top
#define LCD_BACKGROUND_LEFT_TOP_EMPTY 65

#define LCD_BACKGROUND_LEFT_TOP_ONE 18
#define LCD_BACKGROUND_LEFT_TOP_ONE_SELECTED 19

#define LCD_BACKGROUND_LEFT_TOP_TWO 6
#define LCD_BACKGROUND_LEFT_TOP_TWO_1_SELECTED 7
#define LCD_BACKGROUND_LEFT_TOP_TWO_2_SELECTED 8

#define LCD_BACKGROUND_LEFT_TOP_THREE 9
#define LCD_BACKGROUND_LEFT_TOP_THREE_1_SELECTED 10
#define LCD_BACKGROUND_LEFT_TOP_THREE_2_SELECTED 11
#define LCD_BACKGROUND_LEFT_TOP_THREE_3_SELECTED 12

#define LCD_BACKGROUND_LEFT_TOP_FOUR 13
#define LCD_BACKGROUND_LEFT_TOP_FOUR_1_SELECTED 14
#define LCD_BACKGROUND_LEFT_TOP_FOUR_2_SELECTED 15
#define LCD_BACKGROUND_LEFT_TOP_FOUR_3_SELECTED 16
#define LCD_BACKGROUND_LEFT_TOP_FOUR_4_SELECTED 17

// Large lcd icons
#define LCD_ICON_LARGE_WATER 0
#define LCD_ICON_LARGE_FIRE 1
#define LCD_ICON_LARGE_SOAP 2
#define LCD_ICON_LARGE_STORM 3
#define LCD_ICON_LARGE_RESTART 4
#define LCD_ICON_LARGE_PAUSE 5
#define LCD_ICON_LARGE_HOME 72
#define LCD_ICON_LARGE_CABLE 75
#define LCD_ICON_LARGE_TOOLS 79
#define LCD_ICON_LARGE_SNOWFLAKE 82
#define LCD_ICON_LARGE_TIME 86
#define LCD_ICON_LARGE_CONTROLLER 93
#define LCD_ICON_LARGE_LEAF 96

// Small lcd icons
#define LCD_ICON_SMALL_NONE = 0

#define LCD_ICON_SMALL_FIRE 66
#define LCD_ICON_SMALL_PAUSE 67
#define LCD_ICON_SMALL_RESTART 68
#define LCD_ICON_SMALL_SOAP 69
#define LCD_ICON_SMALL_STORM 70
#define LCD_ICON_SMALL_WATER 71
#define LCD_ICON_SMALL_CABLE 76
#define LCD_ICON_SMALL_TOOLS 80
#define LCD_ICON_SMALL_SNOWFLAKE 83
#define LCD_ICON_SMALL_TIME 87
#define LCD_ICON_SMALL_HOME 89
#define LCD_ICON_SMALL_CONTROLLER 94
#define LCD_ICON_SMALL_LEAF 97


// Small lcd selected icons 
#define LCD_ICON_SMALL_SEL_NONE 0

#define LCD_ICON_SMALL_SEL_FIRE 91
#define LCD_ICON_SMALL_SEL_PAUSE 73
#define LCD_ICON_SMALL_SEL_RESTART 78
#define LCD_ICON_SMALL_SEL_SOAP 85
#define LCD_ICON_SMALL_SEL_STORM 92
#define LCD_ICON_SMALL_SEL_WATER 74
#define LCD_ICON_SMALL_SEL_CABLE 77
#define LCD_ICON_SMALL_SEL_TOOLS 81
#define LCD_ICON_SMALL_SEL_SNOWFLAKE 84
#define LCD_ICON_SMALL_SEL_TIME 88
#define LCD_ICON_SMALL_SEL_HOME 90
#define LCD_ICON_SMALL_SEL_CONTROLLER 95
#define LCD_ICON_SMALL_SEL_LEAF 98

#endif